services:
  postgress:
    image: postgres:latest
    container_name: nosso-crescimento
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: ${DB_USER}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_NAME}